### ISSUE TITLE
youtube-dl fails to update due to ssl certificate with python 3.2

### ISSUE THREAD

**Issue by canamcy** [rg3/youtube-dl#16540]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '--verbose']
[debug] Encodings: locale ascii, fs utf-8, out ascii, pref ascii
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.2.2 (CPython) - QNX-8.0.0-MSM8974AA_ES1.1_PVS13SB1_WINDERMEREEMEA_Rev-05-armle-32bit
[debug] exe versions: none
[debug] Proxy map: {}
Traceback (most recent call last):
  File "stage/armle-v7/usr/lib/python3.2/urllib/request.py", line 1136, in do_open
  File "stage/armle-v7/usr/lib/python3.2/http/client.py", line 964, in request
  File "stage/armle-v7/usr/lib/python3.2/http/client.py", line 1002, in _send_request
  File "stage/armle-v7/usr/lib/python3.2/http/client.py", line 960, in endheaders
  File "stage/armle-v7/usr/lib/python3.2/http/client.py", line 805, in _send_output
  File "stage/armle-v7/usr/lib/python3.2/http/client.py", line 743, in send
  File "stage/armle-v7/usr/lib/python3.2/http/client.py", line 1105, in connect
  File "stage/armle-v7/usr/lib/python3.2/ssl.py", line 198, in wrap_socket
  File "stage/armle-v7/usr/lib/python3.2/ssl.py", line 291, in __init__
  File "stage/armle-v7/usr/lib/python3.2/ssl.py", line 287, in __init__
  File "stage/armle-v7/usr/lib/python3.2/ssl.py", line 473, in do_handshake
ssl.SSLError: [Errno 1] _ssl.c:452: error:1409442E:lib(20):func(148):reason(1070)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "youtube_dl.py/youtube_dl/update.py", line 45, in update_self
    newversion = opener.open(VERSION_URL).read().decode('utf-8').strip()
  File "stage/armle-v7/usr/lib/python3.2/urllib/request.py", line 369, in open
  File "stage/armle-v7/usr/lib/python3.2/urllib/request.py", line 387, in _open
  File "stage/armle-v7/usr/lib/python3.2/urllib/request.py", line 347, in _call_chain
  File "youtube_dl.py/youtube_dl/utils.py", line 1101, in https_open
    req, **kwargs)
  File "stage/armle-v7/usr/lib/python3.2/urllib/request.py", line 1139, in do_open
urllib.error.URLError: <urlopen error [Errno 1] _ssl.c:452: error:1409442E:lib(20):func(148):reason(1070)>

ERROR: can't find the current version. Please try again later.

(--no-check-certificate had no effect)
Apparently 3.2 is no longer supported by ytdl. 3.2+ means 3.2 not included?
I wrote a snippet for checking and downloading ytdl version.
This works on 3.2 and although not needed it still works on Win 7 python 3.6.

I found snippets on SO for checking ssl version and TLS version.

ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
handler = urllib.request.HTTPSHandler(context=ctx)
opener = urllib.request.build_opener(handler)
urllib.request.install_opener(opener)
url = YT_DL_URL
response = opener.open(url)

**Comment by dstftw** [comment]
Python prior to 3.4 does not support TLS 1.2 that is now required by GitHub. Thus updating won't work on python <3.4.
