### ISSUE TITLE
Washington Post URL

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5721]
URL: http://www.washingtonpost.com/blogs/the-fix/wp/2015/05/13/the-video-previewing-the-mitt-romney-evander-holyfield-fight-is-amazing/

Output:
C:\>youtube-dl -v "http://www.washingtonpost.com/blogs/the-fix/wp/2015/05/13/the
-video-previewing-the-mitt-romney-evander-holyfield-fight-is-amazing/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.washingtonpost.com/blogs/the-fix
/wp/2015/05/13/the-video-previewing-the-mitt-romney-evander-holyfield-fight-is-a
mazing/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[WashingtonPost] the-video-previewing-the-mitt-romney-evander-holyfield-fight-is
-amazing: Downloading webpage
[WashingtonPost] the-video-previewing-the-mitt-romney-evander-holyfield-fight-is
-amazing: Downloading information of video 1/1
[download] Downloading playlist: The video previewing the Mitt Romney-Evander Ho
lyfield fight is amazing
[WashingtonPost] playlist The video previewing the Mitt Romney-Evander Holyfield
 fight is amazing: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'https://videos.posttv.com/washpost-production/C
harityVision/20150513/5553c882e4b0da740682047b/5553c887e4b0c1092a5bafee_14139176
48266-520npb_t_1431554193559_1920_1080_5400.mp4'
ERROR: unable to download video data: <urlopen error [Errno 1] _ssl.c:510: error
:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1417, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1359, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 59, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1710, in urlopen
  File "urllib2.pyo", line 404, in open
  File "urllib2.pyo", line 422, in _open
  File "urllib2.pyo", line 382, in _call_chain
  File "youtube_dl\utils.pyo", line 713, in https_open
  File "urllib2.pyo", line 1184, in do_open
URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23
_GET_SERVER_HELLO:sslv3 alert handshake failure>

Thanks
Ringo

**Comment by yan12125** [comment]
Washington Post's video server requires a SSL feature called Server Name Indication (SNI). This feature is implemented in Python 2.7.9 and Python 3.x only. Please update your Python to a more recent version.

**Comment by jaimeMF** [comment]
@yan12125 I guess that he's using the windows exe bundled with python 2.7.8.

**Comment by yan12125** [comment]
@jaimeMF Thanks for reminding me of that. Anyway, youtube-dl.exe fails for this case (another example is the audio mentioned in #5366), and I think the Windows binary should be upgraded to Python 2.7.9. Are Windows binaries generated by @phihag?

**Comment by jaimeMF** [comment]
> Are Windows binaries generated by @phihag?

Yes. I hope py2exe doesn't have any issue with python 2.7.9.

**Comment by yan12125** [comment]
See https://www.python.org/downloads/release/python-279/. Most changes in Python 2.7.9 are SSL-related. I think these changes have almost no effects on py2exe, but they are important to youtube-dl.

**Comment by yan12125** [comment]
The latest EXE is built with Python 2.7.10, and this issue can be closed.
