### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ParseError'

### ISSUE THREAD

**Issue by z1atk0** [rg3/youtube-dl#6060]
On a system with Python 2.6, I get the above error (see subject) on an unsupported site which actually works fine with the generic extractor:

[zlatko@disclosure]:~$ youtube-dl -F "http://www.servustv.com/at/Medien/Julies-Geheimnis"
[generic] Julies-Geheimnis: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Julies-Geheimnis: Downloading webpage
[generic] Julies-Geheimnis: Extracting information
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 405, in main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 395, in _real_main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1502, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1069, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 214, in _extract_brightcove_urls
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 122, in _build_brighcove_url
AttributeError: 'module' object has no attribute 'ParseError'
[zlatko@disclosure]:~$ python --version
Python 2.6.2

The same URL/site works fine on a system with Python 2.7:

zlatko@ironman:~/tmp$ ./youtube-dl -F "http://www.servustv.com/at/Medien/Julies-Geheimnis"
[generic] Julies-Geheimnis: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Julies-Geheimnis: Downloading webpage
[generic] Julies-Geheimnis: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Julies Geheimnis bei ServusTV
[generic] playlist Julies Geheimnis bei ServusTV: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Brightcove] 4285283209001: Downloading webpage
[Brightcove] 4285283209001: Extracting information
[info] Available formats for 4285283209001:
format code  extension  resolution note
0            mp4        424x240    412.81MiB
1            mp4        852x480    871.38MiB
2            mp4        1280x720   1.41GiB (best)
zlatko@ironman:~/tmp$ python --version
Python 2.7.3

The youtube-dl version is the same on both systems, 2015.06.15.

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.
