### ISSUE TITLE
I have an issue with [Vice] not working for https, [youtube] does. 

### ISSUE THREAD

**Issue by indywatch** [rg3/youtube-dl#8559]
Not sure how widespread this is, but youtube works with htpps.

> aliasd@melbourne:~$ youtube-dl https://www.vice.com/video/drinking-wine-and-playing-chess-at-martin-shkrelis-midtown-apartment
> [Vice] drinking-wine-and-playing-chess-at-martin-shkrelis-midtown-apartment: Downloading webpage
> ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
> aliasd@melbourne:~$ youtube-dl http://www.vice.com/video/drinking-wine-and-playing-chess-at-martin-shkrelis-midtown-apartment
> [Vice] drinking-wine-and-playing-chess-at-martin-shkrelis-midtown-apartment: Downloading webpage
> [Ooyala] t2bThqMDE6qis5lwVSM1toAKRl5t_CMY: Downloading JSON metadata
> [Ooyala] t2bThqMDE6qis5lwVSM1toAKRl5t_CMY: Downloading mp4 JSON
> [Ooyala] t2bThqMDE6qis5lwVSM1toAKRl5t_CMY: Downloading m3u8 JSON
> ...

Full output...

```
aliasd@melbourne:~$ youtube-dl -v https://www.vice.com/video/drinking-wine-and-playing-chess-at-martin-shkrelis-midtown-apartment
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.vice.com/video/drinking-wine-and-playing-chess-at-martin-shkrelis-midtown-apartment']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.3 - Linux-3.2.0-98-generic-i686-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 0.8.17-4, ffprobe 0.8.17-4, rtmpdump 2.4
[debug] Proxy map: {}
[Vice] drinking-wine-and-playing-chess-at-martin-shkrelis-midtown-apartment: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 354, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 830, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)

```

**Comment by yan12125** [comment]
Could you post the output of the following command:
```
curl -vvv https://www.vice.com/video/drinking-wine-and-playing-chess-at-martin-shkrelis-midtown-apartment
```

**Comment by yan12125** [comment]
For me it works with Python 2.7.11 but fails in Python 2.6.9. I guess it's the same problem as https://github.com/rg3/youtube-dl/issues/5366#issuecomment-93186417 (not checked yet). Could you try again Python 3 or Python 2.7.9+?

**Comment by dstftw** [comment]
For me it fails with 2.6.6, 3.3.4 and works with 2.7.10, 3.4.3.

**Comment by yan12125** [comment]
Confirmed www.vice.com requires SNI (Server Name Indication). To have SNI support in Python, you need both:

* At least Python 2.7.9rc1or Python 3.2.0alpha4
* At least OpenSSL 0.9.8f or 1.0.0

To check whether SNI is available in current Python:
```
python -c "import ssl; print(ssl.HAS_SNI if hasattr(ssl, 'HAS_SNI') else False)"
```
To check whether a website requires SNI or not:
```
echo | openssl s_client -connect www.vice.com:443
echo | openssl s_client -connect www.vice.com:443 -servername www.vice.com
```
If the first command fails while the second is OK, this site require SNI.

For this video, as www.vice.com supports non-HTTPS URLs, so you can download it with:
```
youtube-dl http://www.vice.com/video/drinking-wine-and-playing-chess-at-martin-shkrelis-midtown-apartment
```
Or upgrade/rebuild your Python. There's nothing youtube-dl can do as SNI is a C-level API and we can't implement it in pure Python.
